### ISSUE TITLE
open/close state

### ISSUE THREAD

**Issue by kodibrain** [petealves/homebridge-mqtt-door#1]
Hi, 
the state does not change. Its only shows opening. Did I do something wrong?
	{
	  "accessory": "mqtt-door",
	  "name": "Billardzimmer Tuer",
	  "url": "mqtt://192.168.2.5",
	  "username": "",
	  "password": "",
	  "caption": "BuildingDoor",
	  "topics": {
      "statusGet":  "stat/Billardtuer/POWER",
      "statusSet":  "cmnd/Billardtuer/POWER"
	  },
	  "onValue": "OFF",
	  "offValue": "ON",
	  "statusCmd": "",
	  "integerValue": ""
	},

**Comment by petealves** [comment]
Hello, 
First of all, do you get your door to open at all?
Are you using this to open a dor with a nodemcu or something like that?

**Comment by kodibrain** [comment]
Sure. I use a wemos d1 with tasmota firmware. How does the plugin know when the door is open? Do I need a contact sensor?

**Comment by petealves** [comment]
For what I gathered you are trying to handle states of a door (e.g if the door is opened) right?
At the time that we developed this plugin it wasn't made to recognise if the door is opened or closed. It only does the job of opening the door (0-100%) and closes it right away (100-0%) because we didn't find any plugin to open the door that implemented security.
